on:
  workflow_call:
    secrets:
      context:
        required: true
        description: '(mandatory) Context to use. Available options: [aws, dockerhub]'
      image:
        required: true
        description: (mandatory) Docker image to build
      image_tag:
        required: true
        description: (mandatory) Docker image tag
      aws_access_key_id:
        required: false
        description: (optional) AWS access key ID
      aws_secret_access_key:
        required: false
        description: (optional) AWS secret access key
      aws_default_region:
        required: false
        description: (optional) AWS default region
      repository:
        required: false
        description: (optional) AWS ECR URL
      app_name:
        required: false
        description: (optional) Application name
      dockerhub_username:
        required: false
        description: (optional) DockerHub username
      dockerhub_password:
        required: false
        description: (optional) DockerHub password
      commit_image:
        required: false
        description: (optional) Commit image to DockerHub

jobs:
  build:
    name: Build and push
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS credentials
        if: ${{ secrets.context == 'aws' }}
        run: |
          aws configure set aws_access_key_id ${{ secrets.aws_access_key_id }}
          aws configure set aws_secret_access_key ${{ secrets.aws_secret_access_key }}
          aws configure set region ${{ secrets.aws_default_region }}
      - name: Login to Amazon ECR
        if: ${{ secrets.context == 'aws' }}
        run: |
          aws ecr get-login-password --region ${{ secrets.aws_default_region }} | docker login --username AWS --password-stdin ${{ env.repository }}
      - name: Login to DockerHub
        if: ${{ secrets.context == 'dockerhub' }}
        run: |
          echo ${{ secrets.dockerhub_password }} | docker login -u ${{ secrets.dockerhub_username }} --password-stdin
      - name: Building docker image
        run: |
          docker build -t ${{ secrets.repository }}/${{ secrets.app_name }}:${{ secrets.image_tag }} \
            -t ${{ secrets.repository }}/${{ env.app_name }}:${GITHUB_SHA::7} .
      - name: Pushing docker image
        run: |
          docker push ${{ secrets.repository }}/${{ secrets.app_name }}:${{ secrets.image_tag }}
      - name: Commit image to DockerHub
        if: ${{ secrets.commit_image == 'true' }}
        run: |
          docker push ${{ secrets.repository }}/${{ secrets.app_name }}:${GITHUB_SHA::7}